### ISSUE TITLE
指定最快模型问题

### ISSUE THREAD

**Issue by lizhenen** [no1xuan/HivisionIDPhotos-wechat-weapp#1]
你好，模型指定的为hivision_modnet，ApiServiceImpl里面少写了一个t
![微信图片_20241010140221](https://github.com/user-attachments/assets/986a6462-f97e-4773-a272-b00ee8c4c567)
![微信图片_20241010140240](https://github.com/user-attachments/assets/d266de19-ff36-4d8b-a872-f39416814834)
![微信图片_20241010141811](https://github.com/user-attachments/assets/b8952403-629e-4365-bcd9-99c277de3b80)

**Comment by no1xuan** [comment]
您的细心是对项目成长最大的支持，感谢您！

**Comment by no1xuan** [comment]
已修复，您的细心是对项目成长最大的支持，感谢您！
