### ISSUE TITLE
小程序点击登录，一直显示登录失败

### ISSUE THREAD

**Issue by 2819074731** [no1xuan/HivisionIDPhotos-wechat-weapp#2]
小程序点击登录，一直显示登录失败
![Uploading 微信截图_20241031093754.png…]()

**Comment by no1xuan** [comment]
配置文件没配置好，与后端交互失败就会这样，请查看文档最低部与我联系进行协助

**Comment by 2819074731** [comment]
打扰了，已解决，原来是面板ssl没关闭，数据库连不上

**Comment by no1xuan** [comment]
关面板ssl是因为怕操作面板拖速，对宽带很小的服务器很不友好所以才关闭面板ssl，问题出在数据库连不上
