### ISSUE TITLE
太赞了  找这个找了好久

### ISSUE THREAD

**Issue by Akirassy** [no1xuan/HivisionIDPhotos-wechat-weapp#4]
已经成功部署了  教程很详细  流量主怎么对接呢？

**Comment by no1xuan** [comment]
微信小程序开通流量主需要满500用户，程序仅支持下载证件照的激励视频广告，其它的比如：开屏，封面什么的你可以配合使用微信的智能广告
![image](https://github.com/user-attachments/assets/1f5a16dd-79d8-4b2a-8524-443357e12dc7)

如果你部署了管理员后台，可在系统设置配置：https://github.com/no1xuan/zjzAdmin
![image](https://github.com/user-attachments/assets/07923545-a4a1-450a-b912-af42b589faf9)

如果你没部署管理员后台，可以打开数据库的web_set表配置
![image](https://github.com/user-attachments/assets/9c13d0f7-28e8-4c50-bea8-62f1e093f7ce)
