### ISSUE TITLE
2024.09.25的HivisionIDPhotosde 包里，包含只能抠图和动漫风的功能嘛

### ISSUE THREAD

**Issue by zhixinfang** [no1xuan/HivisionIDPhotos-wechat-weapp#5]
2024.09.25的HivisionIDPhotosde 包里，包含只能抠图和动漫风的功能嘛？还是需要单独搭建

**Comment by no1xuan** [comment]
不包含，并且连抠图都不包含，抠图需要下载模型放到HivisionIDPhotosde里面，其它比如动漫，黑白什么的需要额外单独搭建，请见：https://github.com/no1xuan?tab=repositories

**Comment by no1xuan** [comment]
> 2024.09.25的HivisionIDPhotosde 包里，包含只能抠图和动漫风的功能嘛？还是需要单独搭建

不包含，并且连抠图都不包含，抠图需要下载模型放到HivisionIDPhotosde里面，其它比如动漫，黑白什么的需要额外单独搭建，请见：https://github.com/no1xuan?tab=repositories
